# Generated by Django 3.1.1 on 2020-11-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dato_entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edad', models.IntegerField(max_length=2)),
                ('Sexo', models.CharField(max_length=2)),
                ('Conocimiento_cereales_a', models.CharField(max_length=2)),
                ('Consumio_cereales_e', models.CharField(max_length=2)),
                ('Frecuencia_compra', models.CharField(max_length=2)),
                ('Marca_cereal_consumo', models.CharField(max_length=2)),
                ('Consumio_cereales_a', models.CharField(max_length=2)),
                ('Forma_consumo', models.CharField(max_length=2)),
                ('Interes_aspectos_nutri', models.CharField(max_length=2)),
                ('Influencia_compra', models.CharField(max_length=2)),
                ('Precio_cantidad_apagar', models.CharField(max_length=2)),
                ('Sabor', models.CharField(max_length=2)),
                ('Grupo', models.CharField(max_length=2)),
            ],
        ),
    ]
