# Generated by Django 3.1.1 on 2020-12-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20201107_1508'),
        ('AppLogin', '0001_initial'),
        ('Predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id_Modelo', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_modelo', models.CharField(max_length=20)),
                ('Nombre_modelo', models.CharField(max_length=20)),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Conocimiento_cereales_a',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Consumio_cereales_a',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Consumio_cereales_e',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Edad',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Forma_consumo',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Frecuencia_compra',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Grupo',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Influencia_compra',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Interes_aspectos_nutri',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Marca_cereal_consumo',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Precio_cantidad_apagar',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Sabor',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='Sexo',
        ),
        migrations.RemoveField(
            model_name='dato_entrenamiento',
            name='id',
        ),
        migrations.AddField(
            model_name='dato_entrenamiento',
            name='Grupo_encuesta',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='App1.encuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato_entrenamiento',
            name='id_Dato',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='prediccion',
            fields=[
                ('id_Prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Nro_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLogin.usuario')),
                ('id_Dato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predict.dato_entrenamiento')),
                ('id_Modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predict.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='dato_proyectado',
            fields=[
                ('id_Datop', models.AutoField(primary_key=True, serialize=False)),
                ('Año', models.IntegerField()),
                ('Demanda', models.IntegerField()),
                ('id_Poblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.poblacion')),
                ('id_Prediccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predict.prediccion')),
            ],
        ),
    ]
