# Generated by Django 3.1.1 on 2020-11-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edad', models.IntegerField()),
                ('Sexo', models.CharField(max_length=6)),
                ('Zona', models.CharField(max_length=50)),
                ('Vegano', models.CharField(max_length=2)),
                ('Conocimiento_cereales_a', models.CharField(max_length=2)),
                ('Consumio_cereales_e', models.CharField(max_length=2)),
                ('Frecuencia_compra', models.CharField(max_length=50)),
                ('Momento_consumo', models.CharField(max_length=50)),
                ('Marca_cereal_consumo', models.CharField(max_length=30)),
                ('Consumio_cereales_a', models.CharField(max_length=2)),
                ('Cereal_a_consumido', models.CharField(max_length=50)),
                ('Forma_consumo', models.CharField(max_length=50)),
                ('Interes_aspectos_nutri', models.CharField(max_length=2)),
                ('Influencia_compra', models.CharField(max_length=50)),
                ('Precio_cantidad_apagar', models.CharField(max_length=50)),
                ('Contenido', models.CharField(max_length=20)),
                ('Sabor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='encuestaprueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paterno', models.CharField(max_length=30)),
                ('Materno', models.CharField(max_length=30)),
                ('Nombre', models.CharField(max_length=30)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=25)),
                ('Nro_Usuario', models.IntegerField()),
                ('Estado', models.BooleanField()),
            ],
        ),
    ]
