# Generated by Django 3.1.1 on 2020-11-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0001_initial'),
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Nro_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLogin.usuario'),
        ),
    ]
