# Generated by Django 3.1.1 on 2020-11-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0001_initial'),
        ('App1', '0002_auto_20201105_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='dgeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Cereal', models.IntegerField()),
                ('Anno', models.CharField(max_length=4, verbose_name='Año')),
                ('Lugar', models.CharField(max_length=25)),
                ('Superficie', models.FloatField()),
                ('Produccion', models.FloatField()),
                ('Rendimiento', models.FloatField()),
                ('Cant_exportacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='poblacion',
            fields=[
                ('id_Poblacion', models.AutoField(primary_key=True, serialize=False)),
                ('Localidad', models.CharField(max_length=30)),
                ('Anno', models.CharField(max_length=4, verbose_name='Año')),
                ('Poblacion', models.IntegerField()),
                ('Pea', models.IntegerField()),
                ('Mercado_potencial', models.IntegerField()),
                ('Mercado_objetivo', models.IntegerField()),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='cereal',
            fields=[
                ('id_Cereal', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=25)),
                ('Clase', models.CharField(max_length=25)),
                ('Estado', models.BooleanField()),
                ('Nro_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLogin.usuario')),
            ],
        ),
    ]
