# Generated by Django 3.1.1 on 2020-11-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_cereal_dgeneral_poblacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poblacion',
            old_name='Poblacion',
            new_name='Pet',
        ),
        migrations.AddField(
            model_name='poblacion',
            name='Poblacion_segmentada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
